service: odessa

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, self:custom.defaultRegion}
  environment: ${file(config/environments/${self:provider.stage}.yml)}

package:
  exclude:
    - .env/**
    - .git/**
    - node_modules/**
    - tests/**

custom:
  defaultStage: local
  defaultProfile: default
  defaultRegion: eu-central-1

functions:
  get_device_settings:
    handler: functions/device_settings/handler.get
    events:
      - http:
          path: devices/setting/get
          method: post

  set_device_settings:
    handler: functions/device_settings/handler.set
    events:
      - http:
          path: devices/setting/set
          method: post
