service: odessa

plugins:
 - serverless-dynamodb-local

provider:
  name: aws
  runtime: python3.6
  timeout: 300
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: ${opt:region, self:custom.defaultRegion}
  environment: ${file(config/environments/${self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/*'
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/device_subscriptions'
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/device_logs'
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:dynamodb'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'table/device_network_statuses'
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource:
            - 'arn:aws:s3:::dev-odessa-eu-email/*'
            - 'arn:aws:s3:::qas-odessa-eu-email/*'
            - 'arn:aws:s3:::odessa-eu-email/*'
package:
  exclude:
    - .env/**
    - .git/**
    - node_modules/**
    - tests/**
    - db/**

custom:
  defaultStage: local
  defaultProfile: default
  defaultRegion: local
  httpPath: ${file(config/http_path.js):httpPath.${self:provider.region}}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    migrate:
      dir: ./db/migrations
    seed:
      domain:
        sources:
          - table: service_oids
            sources: [./db/seeds/service_oids.json]
      test_logs_and_notifications:
        sources:
          - table: device_logs
            sources: [./tests/fixtures/logs_and_notifications/device_logs.json]
          - table: device_subscriptions
            sources: [./tests/fixtures/logs_and_notifications/device_subscriptions.json]
          - table: device_network_statuses
            sources: [./tests/fixtures/logs_and_notifications/device_network_statuses.json]
      test_subscriptions:
        sources:
          - table: device_subscriptions
            sources: [./tests/fixtures/subscriptions/device_subscriptions.json]
      test_history_logs:
        sources:
          - table: device_logs
            sources: [./tests/fixtures/history_logs/device_logs.json]
          - table: device_subscriptions
            sources: [./tests/fixtures/history_logs/device_subscriptions.json]
          - table: device_email_logs
            sources: [./tests/fixtures/history_logs/device_email_logs.json]
          - table: reporting_registrations
            sources: [./tests/fixtures/history_logs/reporting_registrations.json]
      test_reporting_registrations:
        sources:
          - table: device_subscriptions
            sources: [./tests/fixtures/reporting_registrations/device_subscriptions.json]
      test_history_statuses:
        sources:
          - table: device_subscriptions
            sources: [./tests/fixtures/history_statuses/device_subscriptions.json]
          - table: reporting_registrations
            sources: [./tests/fixtures/history_statuses/reporting_registrations.json]
          - table: device_network_statuses
            sources: [./tests/fixtures/history_statuses/device_network_statuses.json]

    s3:
      port: 8000
      directory: /tmp
      cors: false

functions:
  get_device_settings:
    handler: functions/device_settings/handler.get
    events:
      - http:
          path: ${self:custom.httpPath}/devices/setting/get
          method: post

  set_device_settings:
    handler: functions/device_settings/handler.set
    events:
      - http:
          path: ${self:custom.httpPath}/devices/setting/set
          method: post

  subscription_info:
    handler: functions/subscriptions/handler.subscription_info
    events:
      - http:
          path: ${self:custom.httpPath}/devices/subscription/log/get
          method: post

  subscribe:
    handler: functions/subscriptions/handler.subscribe
    events:
      - http:
          path: ${self:custom.httpPath}/devices/subscription/log/subscribe
          method: post

  unsubscribe:
    handler: functions/subscriptions/handler.unsubscribe
    events:
      - http:
          path: ${self:custom.httpPath}/devices/subscription/log/unsubscribe
          method: post

  #subscription_stream_trigger:
  #  handler: functions/subscriptions/stream.subscriptions
  #  events:
  #    - stream:
  #        type: dynamodb
  #        arn:
  #          Fn::GetAtt:
  #            - DeviceSubscriptions
  #            - StreamArn
  #        startingPosition: TRIM_HORIZON

  run_subscribe:
    name: run_subscribe
    handler: functions/subscriptions/async.run_subscribe

  run_unsubscribe:
    name: run_unsubscribe
    handler: functions/subscriptions/async.run_unsubscribe

  handle_device_events:
    handler: functions/device_events/handler.handle_device_events

  get_latest_logs:
    handler: functions/device_logs/handler.get_latest_logs
    events:
      - http:
          path: ${self:custom.httpPath}/devices/log/get
          method: post

  save_notify_logs:
    handler: functions/device_notifications/handler.save_notify_logs_db
    events:
      - http:
          path: ${self:custom.httpPath}/devices/log/notify/post
          method: post

  #save_notify_logs_stream_trigger:
  #  handler: functions/device_notifications/stream.save_notify_logs_cache
  #  events:
  #    - stream:
  #        type: dynamodb
  #        arn:
  #          Fn::GetAtt:
  #            - DeviceLogs
  #            - StreamArn
  #        startingPosition: TRIM_HORIZON

  save_notify_status:
    handler: functions/device_notifications/handler.save_notify_status_db

  #save_notify_status_stream_trigger:
  #  handler: functions/device_notifications/stream.save_notify_status_cache
  #  events:
  #    - stream:
  #        type: dynamodb
  #        arn:
  #          Fn::GetAtt:
  #            - DeviceNetworkStatuses
  #            - StreamArn
  #        startingPosition: TRIM_HORIZON

  get_history_logs:
    handler: functions/history_logs/handler.get_history_logs
    events:
      - http:
          path: ${self:custom.httpPath}/devices/log/history
          method: post
          cors: true

  save_reporting_registration:
    handler: functions/reporting_registrations/handler.save_reporting_registration
    events:
      - http:
          path: ${self:custom.httpPath}/devices/report/activation
          method: post

  save_mail_report:
    handler: functions/email_notifications/handler.save_mail_report

  get_history_statuses:
    handler: functions/history_statuses/handler.get_history_statuses
    events:
      - http:
          path: ${self:custom.httpPath}/devices/status/history
          method: post

resources:
  Resources:
    DeviceSubscriptions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: device_subscriptions
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 5
    ServiceOids:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: service_oids
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DeviceNetworkStatuses:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: device_network_statuses
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DeviceLogs:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: device_logs
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ReportingRegistrations:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: reporting_registrations
        AttributeDefinitions:
          - AttributeName: reporting_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: reporting_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DeviceEmailLogs:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: device_email_logs
        AttributeDefinitions:
          - AttributeName: serial_number
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: serial_number
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
