PrintCountFieldMapXML = {
    'DeviceInfo_ModelName': 'Device_Type',
    'DeviceInfo_SerialNumber': 'serial_number',
    'NetInfo_MACAddress': 'Mac_Address',
    'NetInfo_Location': 'Location',
    'NetInfo_Contact': 'Contact',
    'PageCount_Total': 'Total_Page_Count',
    'PageCount_Color': 'Color_Page_Count',
    'PageCount_Monochrome': 'Monochrome_Page_Count',
    'ImageCount_Black': 'Image_Count_Black',
    'ImageCount_Cyan': 'Image_Count_Cyan',
    'ImageCount_Magenta': 'Image_Count_Magenta',
    'ImageCount_Yellow': 'Image_Count_Yellow',
    'ImageCount_Total': 'Image_Count_Total',
    'DeviceCounter_DrumCount': 'Drum_Count',
    'RemainingLife_DrumUnit_Unit_pages': 'Drum_Unit_Remaining_Life',
    'RemainingLife_PaperFeedingKit1_Unit_pages': 'Paper_Feeding_Kit_1_Remaining_Life',
    'RemainingLife_PaperFeedingKit2_Unit_pages': 'Paper_Feeding_Kit_2_Remaining_Life',
    'RemainingLife_PaperFeedingKit3_Unit_pages': 'Paper_Feeding_Kit_3_Remaining_Life',
    'RemainingLife_PaperFeedingKit4_Unit_pages': 'Paper_Feeding_Kit_4_Remaining_Life',
    'RemainingLife_PaperFeedingKitMP_Unit_pages': 'Paper_Feeding_Kit_MP_Remaining_Life',
    'RemainingLife_FuserUnit_Unit_pages': 'Fuser_Unit_Remaining_Life',
    'RemainingLife_BeltUnit_Unit_pages': 'Belt_Unit_Remaining_Life',
    'RemainingLife_LaserUnit_Unit_pages': 'Laser_Unit_Remaining_Life',
    'FaxList_Total': 'Total_Pages_Printed_Fax_List',
    'FaxList_Color': 'Total_Pages_Printed_Color_Fax_List',
    'FaxList_Monochrome': 'Total_Pages_Printed_Monochrome_Fax_List',
    'Copy_Total': 'Total_Pages_Printed_Copy',
    'Copy_Color': 'Total_Pages_Printed_Color_Copy',
    'Copy_Monochrome': 'Total_Pages_Printed_Monochrome_Copy',
    'PCPrint_Total': 'Total_Pages_Printed_PC_Print',
    'PCPrint_Color': 'Total_Pages_Printed_Color_PC_Print',
    'PCPrint_Monochrome': 'Total_Pages_Printed_Monochrome_PC_Print',
    'ScannedCount_ADFSX': 'Total_Pages_Scanned_ADF_1sided',
    'ScannedCount_ADFDX': 'Total_Pages_Scanned_ADF_2sided',
    'ScannedCount_Flatbed': 'Total_Pages_Scanned_Flatbed',
    'ReplaceCount_BlackToner': 'Black_TonerInk_Replace_Count',
    'ReplaceCount_BlackInkReplace': 'Black_TonerInk_Replace_Count',
    'ReplaceCount_CyanToner': 'Cyan_TonerInk_Replace_Count',
    'ReplaceCount_CyanInkReplace': 'Cyan_TonerInk_Replace_Count',
    'ReplaceCount_MagentaToner': 'Magenta_TonerInk_Replace_Count',
    'ReplaceCount_MagentaInkReplace': 'Magenta_TonerInk_Replace_Count',
    'ReplaceCount_YellowToner': 'Yellow_TonerInk_Replace_Count',
    'ReplaceCount_YellowInkReplace': 'Yellow_TonerInk_Replace_Count',
    'ReplaceCount_DrumUnit': 'Drum_Unit_Replace_Count',
    'ReplaceCount_PaperFeedingKit1': 'Paper_Feeding_Kit_1_Replace_Count',
    'ReplaceCount_PaperFeedingKit2': 'Paper_Feeding_Kit_2_Replace_Count',
    'ReplaceCount_PaperFeedingKit3': 'Paper_Feeding_Kit_3_Replace_Count',
    'ReplaceCount_PaperFeedingKit4': 'Paper_Feeding_Kit_4_Replace_Count',
    'ReplaceCount_PaperFeedingKitMP': 'Paper_Feeding_Kit_MP_Replace_Count',
    'ReplaceCount_FuserUnit': 'Fuser_Unit_Replace_Count',
    'ReplaceCount_WasteTonerBox': 'WasteTonerBox_WasteTank_Replace_Count',
    'ReplaceCount_BeltUnit': 'Belt_Unit_Replace_Count',
    'ReplaceCount_LaserUnit': 'Laser_Unit_Replace_Count',
    'JamCount_MPTray': 'Jam_MP_Tray',
    'JamCount_Tray1': 'Jam_Tray_1',
    'JamCount_Tray2': 'Jam_Tray_2',
    'JamCount_Tray3': 'Jam_Tray_3',
    'JamCount_Tray4': 'Jam_Tray_4',
    'JamCount_Inside': 'Jam_Inside',
    'JamCount_Rear': 'Jam_Rear',
    'JamCount_Duplex': 'Jam_2sided',
    'JamCount_Total': 'Jam_Total',
    'JamCount_ADFSX': 'Jam_ADF_1sided',
    'JamCount_ADFDX': 'Jam_ADF_2sided',
    'PageCounterByMediaSize_A5': 'Print_Page_Count_A5',
    'PageCounterByMediaSize_A4Letter': 'Print_Page_Count_A4Letter',
    'PageCounterByMediaSize_B5Executive': 'Print_Page_Count_B5Executive',
    'PageCounterByMediaSize_Envelope': 'Print_Page_Count_Envelopes',
    'Date': 'Date',
    'DeviceReport_DateAndTime': 'Date',
    'ColorDrumCount_Cyan': 'Drum_Count_Cyan',
    'ColorDrumCount_Magenta': 'Drum_Count_Magenta',
    'ColorDrumCount_Yellow': 'Drum_Count_Yellow',
    'ColorDrumCount_Black': 'Drum_Count_Black',
    'ColorDrumUnit_Cyan_Unit_pages': 'Drum_Unit_Cyan_Remaining_Life',
    'ColorDrumUnit_Magenta_Unit_pages': 'Drum_Unit_Magenta_Remaining_Life',
    'ColorDrumUnit_Yellow_Unit_pages': 'Drum_Unit_Yellow_Remaining_Life',
    'ColorDrumUnit_Black_Unit_pages': 'Drum_Unit_Black_Remaining_Life',
    'ColorDrumUnit_Cyan': 'Drum_Unit_Cyan_Replace_Count',
    'ColorDrumUnit_Magenta': 'Drum_Unit_Magenta_Replace_Count',
    'ColorDrumUnit_Yellow': 'Drum_Unit_Yellow_Replace_Count',
    'ColorDrumUnit_Black': 'Drum_Unit_Black_Replace_Count',
    'PageCounterByMediaSize_A3Ledger': 'Print_Page_Count_A3ledgercolor'
}

PrintCountFieldMapCSV = {
    'Device Type': 'Device_Type',
    'Serial Number': 'serial_number',
    'MAC Address': 'Mac_Address',
    'Location': 'Location',
    'Contact': 'Contact',
    'Total Page Count': 'Total_Page_Count',
    'Color Page Count': 'Color_Page_Count',
    'Monochrome Page Count': 'Monochrome_Page_Count',
    'Image Count Black (K)': 'Image_Count_Black',
    'Image Count Cyan (C)': 'Image_Count_Cyan',
    'Image Count Magenta (M)': 'Image_Count_Magenta',
    'Image Count Yellow (Y)': 'Image_Count_Yellow',
    'Image Count Total': 'Image_Count_Total',
    'Total Cut Count': 'Total_Cut_Count',
    'Total Full Cut Count': 'Total_Full_Cut_Count',
    'Total Half Cut Count': 'Total_Half_Cut_Count',
    'Total Print Length (m)': 'Total_Print_Length_m',
    'Drum Count': 'Drum_Count',
    'Drum Count Black (K)': 'Drum_Count_Black',
    'Drum Count Cyan (C)': 'Drum_Count_Cyan',
    'Drum Count Magenta (M)': 'Drum_Count_Magenta',
    'Drum Count Yellow (Y)': 'Drum_Count_Yellow',
    'Drum Unit Remaining Life': 'Drum_Unit_Remaining_Life',
    'Drum Unit Cyan (C) Remaining Life': 'Drum_Unit_Cyan_Remaining_Life',
    'Drum Unit Magenta (M) Remaining Life': 'Drum_Unit_Magenta_Remaining_Life',
    'Drum Unit Yellow (Y) Remaining Life': 'Drum_Unit_Yellow_Remaining_Life',
    'Drum Unit Black (K) Remaining Life': 'Drum_Unit_Black_Remaining_Life',
    'Paper Feeding Kit 1 Remaining Life': 'Paper_Feeding_Kit_1_Remaining_Life',
    'Paper Feeding Kit 2 Remaining Life': 'Paper_Feeding_Kit_2_Remaining_Life',
    'Paper Feeding Kit 3 Remaining Life': 'Paper_Feeding_Kit_3_Remaining_Life',
    'Paper Feeding Kit 4 Remaining Life': 'Paper_Feeding_Kit_4_Remaining_Life',
    'Paper Feeding Kit MP Remaining Life': 'Paper_Feeding_Kit_MP_Remaining_Life',
    'Fuser Unit Remaining Life': 'Fuser_Unit_Remaining_Life',
    'Belt Unit Remaining Life': 'Belt_Unit_Remaining_Life',
    'Laser Unit Remaining Life': 'Laser_Unit_Remaining_Life',
    'Scanner Unit Remaining Life': 'Scanner_Unit_Remaining_Life',
    'Transfer Drum Remaining Life': 'Transfer_Drum_Remaining_Life',
    'Black (K) Coverage': 'Black_Coverage',
    'Cyan (C) Coverage': 'Cyan_Coverage',
    'Magenta (M) Coverage': 'Magenta_Coverage',
    'Yellow (Y) Coverage': 'Yellow_Coverage',
    'Total Pages Printed Fax/List': 'Total_Pages_Printed_Fax_List',
    'Total Pages Printed Color Fax/List': 'Total_Pages_Printed_Color_Fax_List',
    'Total Pages Printed Monochrome Fax/List': 'Total_Pages_Printed_Monochrome_Fax_List',
    'Total Pages Printed Copy': 'Total_Pages_Printed_Copy',
    'Total Pages Printed Color Copy': 'Total_Pages_Printed_Color_Copy',
    'Total Pages Printed Monochrome Copy': 'Total_Pages_Printed_Monochrome_Copy',
    'Total Pages Printed PC Print': 'Total_Pages_Printed_PC_Print',
    'Total Pages Printed Color PC Print': 'Total_Pages_Printed_Color_PC_Print',
    'Total Pages Printed Monochrome PC Print': 'Total_Pages_Printed_Monochrome_PC_Print',
    'Total Pages Scanned ADF(SX)': 'Total_Pages_Scanned_ADF_1sided',
    'Total Pages Scanned ADF(DX)': 'Total_Pages_Scanned_ADF_2sided',
    'Total Pages Scanned Flatbed': 'Total_Pages_Scanned_Flatbed',
    'Black (K) Toner/Ink Replace Count': 'Black_TonerInk_Replace_Count',
    'Cyan (C) Toner/Ink Replace Count': 'Cyan_TonerInk_Replace_Count',
    'Magenta (M) Toner/Ink Replace Count': 'Magenta_TonerInk_Replace_Count',
    'Yellow (Y) Toner/Ink Replace Count': 'Yellow_TonerInk_Replace_Count',
    'Drum Unit Replace Count': 'Drum_Unit_Replace_Count',
    'Drum Unit Cyan (C) Replace Count': 'Drum_Unit_Cyan_Replace_Count',
    'Drum Unit Magenta (M) Replace Count': 'Drum_Unit_Magenta_Replace_Count',
    'Drum Unit Yellow (Y) Replace Count': 'Drum_Unit_Yellow_Replace_Count',
    'Drum Unit Black (K) Replace Count': 'Drum_Unit_Black_Replace_Count',
    'Paper Feeding Kit 1 Replace Count': 'Paper_Feeding_Kit_1_Replace_Count',
    'Paper Feeding Kit 2 Replace Count': 'Paper_Feeding_Kit_2_Replace_Count',
    'Paper Feeding Kit 3 Replace Count': 'Paper_Feeding_Kit_3_Replace_Count',
    'Paper Feeding Kit 4 Replace Count': 'Paper_Feeding_Kit_4_Replace_Count',
    'Paper Feeding Kit MP Replace Count': 'Paper_Feeding_Kit_MP_Replace_Count',
    'Fuser Unit Replace Count': 'Fuser_Unit_Replace_Count',
    'Waste Toner Box Replace Count': 'WasteTonerBox_WasteTank_Replace_Count',
    'Belt Unit Replace Count': 'Belt_Unit_Replace_Count',
    'Laser Unit Replace Count': 'Laser_Unit_Replace_Count',
    'Jam MP Tray (A1)': 'Jam_MP_Tray',
    'Jam Tray1 (A2)': 'Jam_Tray_1',
    'Jam Tray2 (A3)': 'Jam_Tray_2',
    'Jam Tray3 (A4)': 'Jam_Tray_3',
    'Jam Tray4 (A5)': 'Jam_Tray_4',
    'Jam Inside (B)': 'Jam_Inside',
    'Jam Rear (C)': 'Jam_Rear',
    'Jam Duplex (D)': 'Jam_2sided',
    'Jam MailBox (E)': 'Jam_MailBox_Jam_OP_Output_Tray',
    'Jam Total': 'Jam_Total',
    'Jam ADF(SX)': 'Jam_ADF_1sided',
    'Jam ADF(DX)': 'Jam_ADF_2sided',
    'A5': 'Print_Page_Count_A5',
    'A4/Letter': 'Print_Page_Count_A4Letter',
    'B5/Exe': 'Print_Page_Count_B5Executive',
    'Envelopes': 'Print_Page_Count_Envelopes',
}
