BOC_API_CALL_TIMEOUT: '180'
BOC_BASE_URL: 'https://connections.brother.com'
DYNAMO_ENDPOINT_URL: ''
REDIS_ENDPOINT_URL: ''
PROXY: ''
S3_ENDPOINT_URL: ''
S3_ACCESS_KEY: ''
S3_SECRET_KEY: ''
THRESHOLD_TIME_UNIT_BOC: '16' #In Hours
THRESHOLD_TIME_UNIT_EMAIL: '120' #In Hours
STAGE: 'prod'
