BOC_API_CALL_TIMEOUT: '180'
BOC_BASE_URL: 'https://qas-connections.mysora.net'
DYNAMO_ENDPOINT_URL: ''
REDIS_ENDPOINT_URL: ''
PROXY: ''
S3_ENDPOINT_URL: ''
S3_ACCESS_KEY: ''
S3_SECRET_KEY: ''
THRESHOLD_TIME_UNIT_BOC: '16' #In Hours
THRESHOLD_TIME_UNIT_EMAIL: '120' #In Hours
STAGE: 'qas'

# To add more URLs, append the URL in the string like 'URLA, URLB, URLC, etc.' separated by commas
AUTHORIZED_ORIGINS: 'https://qas-boc-mgt01.brother.co.jp'
